name: CI Builds

on:
  # execute on every PR made targeting the branches bellow
  pull_request:
    branches:
      - main

  # execute on every push
  push:

jobs:
  build-cpp:
    name: Build CPP Bindings
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'CMakePresets.json') }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Build bindings
        uses: lukka/run-cmake@v10
        env:
          VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
        with:
          configurePreset: vcpkg
          buildPreset: vcpkg
          buildPresetAdditionalArgs: "['--config Release']"
